---

- name: Run the base installion across all hosts
  hosts: all
  become: yes
  roles:
    - { role: roles/ansible-role-common, tags: ['base', 'common'] }

- name: Setup NFS device
  import_playbook: nfs.yml