---

- name: Let's install base packages for the NAS devices
  hosts: nas
  become: yes
  roles:
    - { role: roles/ansible-role-docker, tags: ['nfs', 'docker'] }
    - { role: roles/setup-nfs, tags: ['nfs', 'setup-nfs'] }